version: '3'
services:
  web: # Ruby on Railsが起動するコンテナ
    build: .
    ports:
      - 3000:3000
      - 1234:1234
      - 26162:26162
    volumes:
      - .:/yoyaku # アプリケーションファイルの同期
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rdebug-ide --host '0.0.0.0' --port 1234 --dispatcher-port 26162 -- bin/rails server -b '0.0.0.0'"
  db:
    image: postgres
    volumes:
      - psgl_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
volumes:
  psgl_data: